language: go

go:
  - "1.x"
  - "1.14"

script:
  -  make clean
  -  make
  -  make clean
  -  make build
  -  make clean
  -  make debugbuild
  -  make clean
#  -  make updatedeps # breaks golangci right now
  -  make citest
