pre:
  steps: |
    set -ex
    go env
    # Download all dependencies before rpm build.
    cd src
    make vendor
    make tools

post:
  install:
    - make
    - gcc
    - golang
  steps: |
    # Using a proxy offers some protection against library makers suddently
    # deleting a git tag in their repo, where go would download libraries.
    export GOPROXY="https://proxy.golang.org,direct"
    make test
    make benchmark
    make racetest
