post:
  install:
    - golang
  steps: |
    export GOPATH=/root/go
    export GOBIN=$GOPATH/bin
    go get -u golang.org/x/lint/golint
    go get -u golang.org/x/tools/cmd/goimports
    curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b /usr/bin v1.17.1
    make citest
