pre:
  exclude: ['el6/x86_64']
  steps: |
    set -ex

    # On EL7 we need to use a the proxy, due to the git version being older than what GO supports when downloading dependencies.
    . /etc/os-release || :
    if [ "$VERSION_ID" == "7" ]; then
      export GOPROXY="https://proxy.golang.org,direct"
    fi
    go env
    # Download all dependencies before rpm build.
    cd src
    make vendor
    make tools

post:
  install:
    - make
    - gcc
    - golang
  steps: |
    # Using a proxy offers some protection against library makers suddently
    # deleting a git tag in their repo, where go would download libraries.
    export GOPROXY="https://proxy.golang.org,direct"
    make test
    make benchmark
    make racetest
