#!/bin/sh
#
# Start / stop lmd
#
# chkconfig: 235 90 10
#
### BEGIN INIT INFO
# Provides:          op5-lmd
# Short-Description: op5 lmd
# Description:       op5 lmd is a cached monitor
### END INIT INFO

. /etc/rc.d/init.d/functions

RETVAL=0
prog="lmd"
piddir=/var/run/lmd
pidfile=$piddir/lmd.pid
exe="/usr/bin/lmd"
args="--config=/etc/op5/lmd/lmd.ini --logfile=/var/log/op5/lmd.log --pidfile=$pidfile"
user="monitor"
lockfile=/var/lock/subsys/op5-lmd

start() {
      # create PID dir if it does not exist
      if [ ! -d $piddir ]; then
            mkdir $piddir
      fi

      chown $user $piddir

      echo -n $"Starting $prog: "
      daemon --user=$user --pidfile=$pidfile " { $exe $args & } "
      RETVAL=$?
      echo

      if [ -d /var/lock/subsys ]; then
            test $RETVAL -eq 0 && touch $lockfile
      fi

      sleep 4
      chmod 660 /opt/monitor/var/rw/live
      return $RETVAL
}

stop() {
      echo -n $"Stopping $prog: "
      killproc -p $pidfile $exe
      RETVAL=$?
      echo
      test $RETVAL -eq 0 && rm -f $lockfile
      return $RETVAL
}

reload() {
      stop
      start
}

restart() {
      stop
      start
}

case "$1" in
      start)
            status -p $pidfile $prog && exit 0
            start
            ;;
      stop)
            status -p $pidfile $prog || exit 0
            stop
            ;;
      restart)
            restart
            ;;
      reload)
            reload
            ;;
      condrestart)
            status -p $pidfile $prog || exit 0
            restart
            ;;
      status)
            status -p $pidfile $prog
            RETVAL=$?
            ;;
      *)
            echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
            RETVAL=1
esac

exit $RETVAL
